openapi: 3.0.1
info:
  title: Object Recognition API
  description: API für das User Management, QR-Code scan und KI lauf starten.
  version: 1.0.0

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: /auth/token
          scopes:
            admin: Admin access
            user: User access

  schemas:
    UserRegister:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [Kunde, Mitarbeiter, Admin]

    UserLogin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string

paths:
  /auth/register:
    post:
      summary: Nutzer registriert sich
      security:
        - OAuth2: [Kunde, Mitarbeiter, Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegister'
      responses:
        '201':
          description: Nutzer registriert
        '404':
          description: Fehler beim registriren

  /auth/login:
    post:
      summary: Nutzer meldet sich an
      security:
        - OAuth2: [Kunde, Mitarbeiter, Admin]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
      responses:
        '200':
          description: Erfolgreich angemeldet mit OAuth token
        '401':
          description: Unauthorized
        '404':
          description: Fehler beim anmelden
      x-rate-limit:
        limit: 10

  /auth/logout:
    post:
      summary: Nutzer meldet sich ab, der Zugriffstoken und die Session werden invalide
      security:
        - OAuth2: [Kunde, Mitarbeiter, Admin]
      responses:
        '200':
          description: Erfolgreich abgemeldet
        '404':
          description: Fehler beim abmelden