import enum

class DriveFolders(enum.Enum):
    MODELS = "1epkWoGNRCWeHZbrqMW6okGcmhde1yLQy"  # Replace with actual folder ID
    KIModelle = "13HRqvGLxjQtZwxrOoJQR9JvenIWiQheg"
    Datasets = "1w35_EVX5okPYtZGivVCXQJ-2nWbW1RNQ"
    UPLOAD = "1xoA3-4RWkeizafEYUqfovjgD6Q3oSR7q"
    TRAININGSSATZ = "1BV9kt1H9r9qSUcVAcFjSxFWvOxFfDwYm"
    Datasets_FFv1 = "1Tiw3S-Q2qo85x6mfl6cgMHZVv6nwl1fX"
    Datasets_FFv1_test = "1IbNv1CAXiq8YHVsgql-Vv76pZ1-HnFIe"
    Datasets_FFv1_valid = "18Ttcc8aZ9SMk3FnkrqD-Tp1R2F8ZPxAy"
    Datasets_FFv1_test_labels = "1IbNv1CAXiq8YHVsgql-Vv76pZ1-HnFIe"
    Datasets_FFv1_test_images = "1IbNv1CAXiq8YHVsgql-Vv76pZ1-HnFIe"
    Datasets_FFv1_valid_images = "1GcyMb-yKaE8Sor5sYS1Jjx_b8OAQKMlJ"
    KIModelle_trainiert_mit_ganzem_Datensatz = "1pMRcbhDr0DHNDWD-Nf01zhqNCKhAyYgC"
    DATA = "1BsgVTHe48xN-lKKPEz7LNwC_4yAoNrVV"
    DATA_ObstGemuese_Neu = "1XyofiXvobyc22wrJeXLHbSO0p2Q3fO5v"
    DATA_ObstGemuese_Neu_1_TRAIN= "1S1QkbMxfC62WlOWd5dObBVKZA6APwVTI"
    DATA_ObstGemuese_Neu_1_TRAIN_Tomate = "13w6zH_SqxUle3ULVXWLZ-gGdS4Gp9vTp"
    DATA_ObstGemuese_Neu_1_TRAIN_Paprika = "1EnVek1Psm1fqnGKqTuDBMYCaQ57cX5g0"
    DATA_ObstGemuese_Neu_1_TRAIN_Orange = "19wYOKUNBUN2tkjAftPjYJFkmhTSr7Ptj"
    DATA_ObstGemuese_Neu_1_TRAIN_Kaki = "1IifRBJACj9wTaE-om06041mijQ20FRew"
    DATA_ObstGemuese_Neu_1_TRAIN_Aubergine = "1YzfuuU7LQ60TtY3q5E8gTIHh5HOpo4kB"
    DATA_ObstGemuese_Neu_1_TRAIN_Apfel = "1DIgTbgJ5jldZoYSIZ3Nax1INQ85aRIhX"
    DATA_ObstGemuese_Neu_2_TEST = "1iCjiMPaujobZ3ricQVhGGnx-P6unSEiA"
    DATA_ObstGemuese_Neu_2_TEST_Tomate = "1l4tEoeMmVf2vpyuazQlFvwJFe_yqkVJe"
    DATA_ObstGemuese_Neu_2_TEST_Paprika = "1KSCtcctcSdW-w8QzetBm9UutfQhNVHGJ"
    DATA_ObstGemuese_Neu_2_TEST_Orange = "1OLA6DTxEA5sCsGiAubK9xe_SFebE-qSx"
    DATA_ObstGemuese_Neu_2_TEST_Kaki = "1_0ywE-rIQ33NiidYHaWP8gvrYKyUHkMc"
    DATA_ObstGemuese_Neu_2_TEST_Aubergine = "18MQuO9kSgyg3vyRJ5oI8b5z6LNoodALI"
    DATA_ObstGemuese_Neu_2_TEST_Apfel = "1TsZVycRQGiDbgJ1q9EijZqqayGOUwvp6"
    DATA_ObstGemuese_Neu_3_VALIDATE = "1jyBpCYB6zeCnFKRsDVTNI0L_RrYCHB-P"
    DATA_ObstGemuese_Neu_3_VALIDATE_Tomate = "1haXXHmCT6hL7MUT20n45ck1MtYwX6yU5"
    DATA_ObstGemuese_Neu_3_VALIDATE_Paprika = "1rWZJw4UTX1gNcDb5hmntAUryPDoY5cjZ"
    DATA_ObstGemuese_Neu_3_VALIDATE_Orange = "1gBMNoBOwCZzhYNi1vBqhrbQbToX-N9VY"
    DATA_ObstGemuese_Neu_3_VALIDATE_Kaki = "1duSK6Dp8uVt7iig4mwMRhj1aMZ6aX5aJ"
    DATA_ObstGemuese_Neu_3_VALIDATE_Aubergine = "1vbDaWXJrxpmyvi2GHYgq2SQCKvnF-x_e"
    DATA_ObstGemuese_Neu_3_VALIDATE_Apfel = "1hbF9KYk_QLV7VXYk2InjcVW4Pocs0Oze"
