name: Code Style Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  code-style-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Pylint
        run: pip install pylint

      - name: Run Pylint
        run: |
          # Run Pylint only on Python files in src or app folders
          pylint src/**/*.py app/**/*.py || pylint main.py
        continue-on-error: false # Fail if there are any linting errors

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Prettier
        run: npm install prettier

      - name: Run Prettier
        run: npx prettier --check "**/*.{js,jsx,ts,tsx,css,html,json}"